---
title: "U.S. Energy Poverty and Temperature"
author: "Desik Somasundaram"
date: "11/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```


```{r data read}
# Read in data
educ_df <- read_csv(here("data", "Education.csv"), skip = 4)
county_health <- read_csv(here("data", "analytic_data2021.csv"), skip = 1)
temp_avg_df <- read_csv(here("data", "temp", "110-tavg-201501-60.csv"), skip = 3,)
temp_min_df <- read_csv(here("data", "temp", "110-tmin-201501-60.csv"), skip = 3,show_col_types = FALSE)
temp_max_df <- read_csv(here("data", "temp", "110-tmax-201501-60.csv"), skip = 3,show_col_types = FALSE)
LEAD_df <-
    list.files(path = here("data", "LEAD"), pattern = "*.csv") %>% 
    map_df(~read_csv(here("data", "LEAD",.), skip = 7,show_col_types = FALSE))
```

## Including Plots

You can also embed plots, for example:

```{r data wrangling}
# Clean temp data to prepare for join
temp_avg_df <- temp_avg_df %>%
               rename(t_avg = Value) %>% 
               select(1:3)
temp_min_df <- temp_min_df %>%
               rename(t_min = Value) %>% 
               select(1:3)
temp_max_df <- temp_max_df %>%
               rename(t_max = Value) %>% 
               select(1:3)
```


```{r}
# Join temperature statistics data
join_temp<-temp_avg_df %>% 
  full_join(temp_min_df, by= c("Location ID", "Location")) %>%       
  full_join(temp_max_df, by= c("Location ID", "Location")) %>% 
  separate(`Location ID`, 
                c("State", "FIP-End")) %>% 
  rename("Area name" = Location)
# Clean education data
educ_df <- educ_df %>% 
           drop_na(State, "2003 Urban Influence Code") %>% 
           filter(State != "PR") %>% 
           select(-ends_with(c("1970","1980", "1990", "2000"))) %>% 
           select(-starts_with(c("2003","2013")))
# Clean LEAD energy affordability data
LEAD_df <- LEAD_df %>% 
           mutate(`FIPS Code` = (gsub("'", "",(LEAD_df$`Geography ID`)))) %>% 
           subset(select= -c(`Geography ID`))
```

```{r}
# Join LEAD, temp and education data
energy_edu_temp<- join_temp %>% 
                  left_join(educ_df, by= c("State", "Area name")) %>% 
                  full_join(LEAD_df, by= "FIPS Code")%>% 
                  subset(select= -c(`FIP-End`,Name)) %>% 
                  clean_names()

energy_edu_temp <- energy_edu_temp %>% 
                   mutate(comf_diff_temp = (72 - t_avg)) 

all_param <- energy_edu_temp %>% 
             rename(fipscode = fips_code) %>% 
             full_join(county_health, by= "fipscode")
  

```

```{r}
statefacts <- as.data.frame(state.x77)
stateregion <- as.data.frame(state.region)
stateabb <- as.data.frame(state.abb)
statefacts <- statefacts %>% 
  cbind(stateregion) %>% 
  cbind(stateabb) %>% 
  rename(region = state.region) %>% 
  rename(state = state.abb)

energy_edu_temp<- energy_edu_temp %>% 
                  left_join(statefacts, by= "state")

```


```{r}
summary(lm(energy_edu_temp$percent_of_adults_with_less_than_a_high_school_diploma_2015_19 ~ energy_edu_temp$avg_energy_burden_percent_income + energy_edu_temp$t_avg))
```
```{r}
summary(lm(all_param$v160_rawvalue ~ all_param$avg_energy_burden_percent_income + all_param$comf_diff_temp))
```

```{r}
plot(energy_edu_temp$percent_of_adults_with_a_bachelors_degree_or_higher_2015_19 ~ energy_edu_temp$avg_energy_burden_percent_income + energy_edu_temp$t_max, data = energy_edu_temp)

```

